@startuml
class com.patch4code.loglinemovieapp.features.home.presentation.screen_home.HomeViewModel {
- TmdbApiService tmdbApiService
-  _isLoading
+ LiveData<Boolean> isLoading
-  _popularMovies
-  _topRatedMovies
-  _upcomingMovies
-  _homeMoviesMap
+ LiveData<Map<UiText.StringResource, List<Movie>>> homeMoviesMap
+ void loadHomeViewData()
- void updateHomeMovieMap()
}




androidx.lifecycle.ViewModel <|-- com.patch4code.loglinemovieapp.features.home.presentation.screen_home.HomeViewModel
@enduml