name: build-apk

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'

      - name: "build release apk"
        run: ./gradlew assembleRelease --stacktrace

      - name: "upload apk"
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: app/build/outputs/apk/release/*.apk
